version: '3'

services:

    # mongodb:
    #     image: mongo
    #     container_name: mongodb
    #     restart: always
    #     volumes:
    #         - mongodata:/data/db

    reptile-web-api:
        build: ./web-api
        container_name: reptile-web-api
        # depends_on:
        #     - mongodb
        ports:
            - 8080:8080
        environment:
            - HOST_NAME=192.168.50.32:27100
            - DB_NAME=hr
            # - HOST_NAME=192.168.1.65:27100
            # - DB_NAME=human_resource
            - DEBUG=express:router
        restart: always

    reptile-crawler:
        build: ./crawler
        container_name: reptile-crawler
        depends_on:
            - reptile-web-api
        environment:
            - CYPRESS_baseUrl=http://192.168.50.32:8080
        # command: npx cypress run -s /app/cypress/integration/hr/workDate_aDay.js -b chrome
        command: sh -c "reptile.sh"

# volumes:
#     mongodata:
