version: '3'

services:
  reptile-web-api:
    image: reptile-web-api
    container_name: reptile-web-api
    depends_on:
      - mongodb
    environment:
      - HOST_NAME=mongodb:27017
      - DEBUG=express:router
      - TZ=Asia/Taipei
    restart: always

  reptile-crawler:
    image: reptile-crawler
    container_name: reptile-crawler
    depends_on:
      - reptile-web-api
    environment:
      - CYPRESS_baseUrl=http://reptile-web-api:8080
      - TZ=Asia/Taipei

networks:
  default: moonshine-net
