version: '3'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        volumes:
            - mongodata:/data/db
        environment:
            - TZ=Asia/Taipei

    reptile-web-api:
        build: ./web-api
        container_name: reptile-web-api
        depends_on:
            - mongodb
        ports:
            - 8080
        environment:
            - HOST_NAME=mongodb:27017
            - DB_NAME=hr
            - DEBUG=express:router
            - TZ=Asia/Taipei
        restart: always

    reptile-crawler:
        build: ./crawler
        container_name: reptile-crawler
        depends_on:
            - reptile-web-api
        environment:
            - CYPRESS_baseUrl=http://reptile-web-api:8080
            - TZ=Asia/Taipei

volumes:
    mongodata:
